In [2]:
import pandas as pd
import numpy as np
from dateutil.parser import parse
import datetime

def accounting_sheet(file_name):
    #data = pd.read_excel(file_name)
    data = pd.read_csv(file_name)
    # Drop rows by index
    data.drop(data.index[0:14], inplace=True)
    # Drop all empty columns
    data.dropna(how='all', axis=1, inplace=True)
    # Drop all empty rows
    data.dropna(how='all', axis=0, inplace=True)

    #creating empty columns
    data['time'] = ''
    data['date'] = ''
    
    # seperating date from time
    for i in range(0, len(data),1):
        if ':' in data['Unnamed: 2'].iloc[i]:
            data['time'].iloc[i] = data['Unnamed: 2'].iloc[i]
        elif ' ' in data['Unnamed: 2'].iloc[i]:
            data['date'].iloc[i] = data['Unnamed: 2'].iloc[i]   
        else:
            continue


    # Fill whitespaces with NaN
    data.replace(r'^\s*$', np.nan, regex=True,inplace = True)

    # forward fill - fill next row values with value before
    data['date'].fillna(method='ffill', inplace=True)

    # converting year month strings to date
    data['dates'] = data['date'].map(lambda d: parse(d + '2022'))


    data['Unnamed: 2'].iloc[0] = 'previous_time'
    data['time'].iloc[0] = 'time'
    data['date'].iloc[0] = 'date'
    data['dates'].iloc[0] = 'dates'
    #setting first row as header
    data.columns = data.iloc[0]

    #setting null positions in previous time to string value: remove
    for i in range(0, len(data),1):
        if ':' not in data['previous_time'].iloc[i]:
            data['previous_time'].iloc[i] = 'remove'
        else:
            continue
    #dropping rows where previous_time = remove
    data = data[data['previous_time'] != 'remove'].copy()

    # Remove special characters
    data['Money In'] = data['Money In'].replace({'₦': '', ',':''}, regex=True)
    data['Money out'] = data['Money out'].replace({'₦': '', ',':''}, regex=True)
    data['Balance'] = data['Balance'].replace({'₦': '', ',':''}, regex=True)
    #convert string columns to float
    data['Money In'] = data['Money In'].astype(float)
    data['Money out'] = data['Money out'].astype(float)
    data['Balance'] = data['Balance'].astype(float)
    #convert string column to date
    data['dates'] = pd.to_datetime(data['dates'],format="%Y/%m/%d")
    #convert string colum to time only
    data['previous_time'] = pd.to_datetime(data['previous_time'],format= '%H:%M:%S' ).dt.time
    #Ordering the dataframe columns
    data = data[['dates', 'previous_time', 'Money In', 'Money out', 'Category', 'To / From','Description', 'Balance']]
    #returning a csv file
    return data.to_csv('cleaned_accounting_sheet.csv', index = False)

accounting_sheet('Kuda Statement.csv')

C:\Users\eoder\anaconda3\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [3]:
pd.read_csv('cleaned_accounting_sheet.csv')

,dates,previous_time,Money In,Money out,Category,To / From,Description,Balance
0,2022-07-16,02:16:54,NaN,100.00,outward transfer,Bolaji Oluwatiata purchase - 8118087247,"₦539,411.22",NaN
1,2022-07-16,02:18:11,NaN,100.00,outward transfer,ji O35565927|[reversal]data purchase - 8118087247,"₦539,311.22",NaN
2,2022-07-16,02:19:21,NaN,100.00,outward transfer,ji Oluwatimilehin742933238|[reversal]data purc...,"₦539,211.22",NaN
3,2022-07-16,02:40:48,NaN,1000.00,outward transfer,power purchase - 62141117606,"₦538,211.22",NaN
4,2022-07-16,06:40:29,NaN,5000.00,outward transfer,imoh reversal]power purchase - 0101150401459,"₦533,211.22",NaN
5,2022-07-16,06:48:45,NaN,5000.00,outward transfer,Akanimoh Collinsrsal]power purchase - 01011504...,"₦528,211.22",NaN
6,2022-07-16,19:10:13,NaN,100.00,outward transfer,(Lumi)-Arogundade Oluwafunke/2039345844/Kuda,wallet migration,481573.18
7,2022-07-17,06:13:53,NaN,100.00,outward transfer,(Lumi)-Anietie Owo Idohoabasi/2039367897/Kuda,wallet migration,481473.18
8,2022-07-17,09:10:09,NaN,27.62,outward transfer,(Lumi)-Rush-E Essentials/2038402607/Kuda,webhookignore|22754193|transfer fee reversal,481445.56
9,2022-07-18,15:35:37,NaN,20.00,outward transfer,Emmanuel/20309/Kuda,wallet migration,481425.56
10,2022-07-18,15:36:32,NaN,100.00,outward transfer,Kenneth/20354/Kuda,wallet migration,481325.56
11,2022-07-18,17:17:26,NaN,50.00,outward transfer,Yinka/20393/Kuda,wallet migration,481275.56
12,2022-07-18,18:37:33,NaN,2500.00,outward transfer,Damola/20369/Kuda,webhookignore|41591961|[reversal]power purchas...,478775.56
13,2022-07-18,21:16:17,NaN,1.00,outward transfer,Temitope/20398/Kuda,wallet migration,478774.56
14,2022-07-19,14:05:29,NaN,10.00,outward transfer,Ayomide/20315/Kuda,wallet migration,478764.56
15,2022-07-19,16:35:36,NaN,20.00,outward transfer,Abdulfatahi532165/Kuda,wallet migration,478744.56
16,2022-07-19,18:41:08,NaN,30.00,outward transfer,olulope/20621/Kuda,wallet migration,478714.56
17,2022-07-19,20:36:13,NaN,200.00,outward transfer,Juliet/20967/Kuda,wallet migration,478514.56
18,2022-07-19,22:35:26,NaN,200.00,outward transfer,inglocha Charity/22743/Kuda,wallet migration,478314.56
19,2022-07-19,22:44:29,NaN,400.00,outward transfer,dams Opeyemi/20359/Kuda,wallet migration,477914.56
20,2022-07-20,19:46:24,NaN,100.00,outward transfer,dowu/20160/Kuda,wallet migration,477814.56
21,2022-07-20,21:58:17,NaN,100.00,outward transfer,kwue Uche/16832/Kuda,wallet migration,477714.56
22,2022-07-20,22:01:59,NaN,101.00,outward transfer,amuel/20035/Kuda,wallet migration,477613.56
23,2022-07-20,22:22:57,NaN,300.00,outward transfer,kodunmi Titilayo/28094/Kuda,wallet migration,477313.56
24,2022-07-21,10:18:22,200.0,NaN,outward transfer,em/2036/Kuda,airtime purchase - +2347062024222,477513.56
25,2022-07-21,11:15:34,NaN,10.00,outward transfer,nia/2031/Kuda,wallet migration,477503.56
26,2022-07-21,11:44:56,NaN,60.00,outward transfer,otun/2041/Kuda,wallet migration,477443.56
27,2022-07-21,12:46:15,NaN,30.00,outward transfer,siu/2031/Kuda,wallet migration,477413.56
28,2022-07-21,15:49:00,NaN,100.00,outward transfer,i/20396Kuda,wallet migration,477313.56
29,2022-07-21,18:55:28,NaN,1000.00,outward transfer,2035128da,webhookignore|9911677181|[reversal]power purch...,476313.56
30,2022-07-21,19:12:02,NaN,1000.00,outward transfer,2035128da,webhookignore|37211156626|[reversal]power purc...,475313.56
31,2022-07-21,19:13:29,NaN,1000.00,outward transfer,2035128da,webhookignore|6589895669|[reversal]power purch...,474313.56